---
# The shelly component is to integrate Shelly https://shelly.cloud devices into home assistant.
# This uses the custom component loaded through hacs
#
# https://github.com/StyraHem/ShellyForHASS
#
shelly:
  discovery: true  #add all devices (default)
  devices: !include_dir_list ../entities/shelly

