---
# Switch to turn on/off Chlorinator

platform: mqtt
name: "SWG"
state_topic: !secret swg_power_state_topic
command_topic: !secret swg_power_command_topic
payload_on: "1"
payload_off: "0"
state_on: "2"
state_off: "0"
icon: mdi:water-outline